name: 'DDF Validator action'
description: 'Validate all DDf in directory.'
author: 'Zehir'
branding:
  icon: 'check'
  color: 'green'
inputs:
  directory:
    required: true
    description: 'input directory of DDF files'
  generic:
    required: false
    description: 'input directory of Generic files, will look for a "generic" folder in main directory if ommited'
  search:
    required: false
    description: 'input search pattern'
    default: '**/*.json'
  ignore:
    required: false
    description: 'ignore files that match this pattern'
  no-skip:
    required: false
    description: 'Validate all files even if they have the ddfvalidate option to false'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
