# `dist/index.js` is a special file in Actions.
# When you reference an action with `uses:` in a workflow,
# `index.js` is the code that will run.
# For our project, we generate this file through a build process from other source files.
# We need to make sure the checked-in `index.js` actually matches what we expect it to be.
name: Continuous integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build
        run: pnpm build

      - name: Test
        uses: ./
        with:
          directory: tests
          generic: tests/generic
          search: '**/*.json'
          ignore: '**/generic/**'

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release tags
        uses: JasonEtco/build-and-tag-action@v2
        if: steps.changesets.outcome == 'success' && steps.changesets.outputs.published == 'true'
        with:
          tag_name: ${{ format('v{0}', fromJSON(steps.changesets.outputs.publishedPackages)[0].version) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
